root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "vendor", "bin"]
delay = 500
stop_on_error = true

[log]
time = true
